name: obligation-tracker-green
services:
  backend-green:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: obligation-backend-green
    restart: always
    ports:
      - "3002:3000"
    networks:
      green-net:
        aliases:
          - backend
    environment:
      - NODE_ENV=production
      - APP_COLOR=green
      - PORT=3000
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - ./backend/.env

  frontend-green:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: obligation-frontend-green
    restart: always
    ports:
      - "8082:80"
    networks:
      - green-net
    depends_on:
      - backend-green

networks:
  green-net: