services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: obligation-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: obligation-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend